/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CarreirasRouteImport } from './routes/carreiras'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ManifestDotjsonRouteImport } from './routes/manifest[.]json'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as MetodoRouteImport } from './routes/metodo'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as SitemapImagensDotxmlRouteImport } from './routes/sitemap-imagens[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAcademyRouteImport } from './routes/app.academy'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppAdvisorRouteImport } from './routes/app.advisor'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAtivosRouteImport } from './routes/app.ativos'
import { Route as AppAuditoriaRouteImport } from './routes/app.auditoria'
import { Route as AppAutomacoesRouteImport } from './routes/app.automacoes'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppClientesRouteImport } from './routes/app.clientes'
import { Route as AppComportamentoRouteImport } from './routes/app.comportamento'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppConstrutorasRouteImport } from './routes/app.construtoras'
import { Route as AppConteudosRouteImport } from './routes/app.conteudos'
import { Route as AppCorretoresRouteImport } from './routes/app.corretores'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppDecisoesRouteImport } from './routes/app.decisoes'
import { Route as AppEcossistemaRouteImport } from './routes/app.ecossistema'
import { Route as AppEquipesRouteImport } from './routes/app.equipes'
import { Route as AppErpRouteImport } from './routes/app.erp'
import { Route as AppExecutiveRouteImport } from './routes/app.executive'
import { Route as AppFabricRouteImport } from './routes/app.fabric'
import { Route as AppFeedbackRouteImport } from './routes/app.feedback'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppFunisRouteImport } from './routes/app.funis'
import { Route as AppGonogoRouteImport } from './routes/app.gonogo'
import { Route as AppIaRouteImport } from './routes/app.ia'
import { Route as AppImportarRouteImport } from './routes/app.importar'
import { Route as AppInstitucionalRouteImport } from './routes/app.institucional'
import { Route as AppKnowledgeRouteImport } from './routes/app.knowledge'
import { Route as AppLandingRouteImport } from './routes/app.landing'
import { Route as AppLeadsSiteRouteImport } from './routes/app.leads-site'
import { Route as AppMarketingRouteImport } from './routes/app.marketing'
import { Route as AppMemoriaRouteImport } from './routes/app.memoria'
import { Route as AppMercadoRouteImport } from './routes/app.mercado'
import { Route as AppMidiaRouteImport } from './routes/app.midia'
import { Route as AppOportunidadesRouteImport } from './routes/app.oportunidades'
import { Route as AppOrganizacaoRouteImport } from './routes/app.organizacao'
import { Route as AppOrquestracaoRouteImport } from './routes/app.orquestracao'
import { Route as AppPermissoesRouteImport } from './routes/app.permissoes'
import { Route as AppPessoasRouteImport } from './routes/app.pessoas'
import { Route as AppPilotoRouteImport } from './routes/app.piloto'
import { Route as AppPlatformRouteImport } from './routes/app.platform'
import { Route as AppPortalClienteRouteImport } from './routes/app.portal-cliente'
import { Route as AppRadarRouteImport } from './routes/app.radar'
import { Route as AppRelatoriosRouteImport } from './routes/app.relatorios'
import { Route as AppTelemetriaRouteImport } from './routes/app.telemetria'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ConstrutorasCuryRouteImport } from './routes/construtoras.cury'
import { Route as EmpreendimentosIndexRouteImport } from './routes/empreendimentos.index'
import { Route as EmpreendimentosIdRouteImport } from './routes/empreendimentos.$id'
import { Route as EmpreendimentosCuryRouteImport } from './routes/empreendimentos.cury'
import { Route as EnSplatRouteImport } from './routes/en.$'
import { Route as EsSplatRouteImport } from './routes/es.$'
import { Route as LpSlugRouteImport } from './routes/lp.$slug'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AppAdminIndexRouteImport } from './routes/app.admin.index'
import { Route as AppAdminHealthRouteImport } from './routes/app.admin.health'
import { Route as AppEmpreendimentosIndexRouteImport } from './routes/app.empreendimentos.index'
import { Route as AppPessoasIndexRouteImport } from './routes/app.pessoas.index'
import { Route as AppPessoasIdRouteImport } from './routes/app.pessoas.$id'
import { Route as EmpreendimentosCuryIndexRouteImport } from './routes/empreendimentos.cury.index'
import { Route as EmpreendimentosCurySlugRouteImport } from './routes/empreendimentos.cury.$slug'
import { Route as EmpreendimentosCuryCompararRouteImport } from './routes/empreendimentos.cury.comparar'
import { Route as EmpreendimentosCuryMapaRouteImport } from './routes/empreendimentos.cury.mapa'
import { Route as ApiPublicHooksAdvisorWatchdogRouteImport } from './routes/api/public/hooks/advisor-watchdog'
import { Route as ApiPublicHooksAutomationRollupRouteImport } from './routes/api/public/hooks/automation-rollup'
import { Route as ApiPublicHooksMarketCollectorRouteImport } from './routes/api/public/hooks/market-collector'
import { Route as ApiPublicHooksOutboxWorkerRouteImport } from './routes/api/public/hooks/outbox-worker'
import { Route as AppEmpreendimentosIdPropertyRouteImport } from './routes/app.empreendimentos.$id.property'
import { Route as AppEmpreendimentosIdUnidadesRouteImport } from './routes/app.empreendimentos.$id.unidades'
import { Route as EmpreendimentosCurySlugIndexRouteImport } from './routes/empreendimentos.cury.$slug.index'
import { Route as EmpreendimentosCurySlugLandingRouteImport } from './routes/empreendimentos.cury.$slug.landing'
import { Route as EmpreendimentosCurySlugUnidadeUnidadeIdRouteImport } from './routes/empreendimentos.cury.$slug.unidade.$unidadeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasRoute = CarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotjsonRoute = ManifestDotjsonRouteImport.update({
  id: '/manifest.json',
  path: '/manifest.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoRoute = MetodoRouteImport.update({
  id: '/metodo',
  path: '/metodo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagensDotxmlRoute = SitemapImagensDotxmlRouteImport.update({
  id: '/sitemap-imagens.xml',
  path: '/sitemap-imagens.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademyRoute = AppAcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvisorRoute = AppAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAtivosRoute = AppAtivosRouteImport.update({
  id: '/ativos',
  path: '/ativos',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomacoesRoute = AppAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppComportamentoRoute = AppComportamentoRouteImport.update({
  id: '/comportamento',
  path: '/comportamento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConstrutorasRoute = AppConstrutorasRouteImport.update({
  id: '/construtoras',
  path: '/construtoras',
  getParentRoute: () => AppRoute,
} as any)
const AppConteudosRoute = AppConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AppRoute,
} as any)
const AppCorretoresRoute = AppCorretoresRouteImport.update({
  id: '/corretores',
  path: '/corretores',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisoesRoute = AppDecisoesRouteImport.update({
  id: '/decisoes',
  path: '/decisoes',
  getParentRoute: () => AppRoute,
} as any)
const AppEcossistemaRoute = AppEcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipesRoute = AppEquipesRouteImport.update({
  id: '/equipes',
  path: '/equipes',
  getParentRoute: () => AppRoute,
} as any)
const AppErpRoute = AppErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AppRoute,
} as any)
const AppExecutiveRoute = AppExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => AppRoute,
} as any)
const AppFabricRoute = AppFabricRouteImport.update({
  id: '/fabric',
  path: '/fabric',
  getParentRoute: () => AppRoute,
} as any)
const AppFeedbackRoute = AppFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppFunisRoute = AppFunisRouteImport.update({
  id: '/funis',
  path: '/funis',
  getParentRoute: () => AppRoute,
} as any)
const AppGonogoRoute = AppGonogoRouteImport.update({
  id: '/gonogo',
  path: '/gonogo',
  getParentRoute: () => AppRoute,
} as any)
const AppIaRoute = AppIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AppRoute,
} as any)
const AppImportarRoute = AppImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AppRoute,
} as any)
const AppInstitucionalRoute = AppInstitucionalRouteImport.update({
  id: '/institucional',
  path: '/institucional',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppLandingRoute = AppLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsSiteRoute = AppLeadsSiteRouteImport.update({
  id: '/leads-site',
  path: '/leads-site',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriaRoute = AppMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AppRoute,
} as any)
const AppMercadoRoute = AppMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => AppRoute,
} as any)
const AppMidiaRoute = AppMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AppRoute,
} as any)
const AppOportunidadesRoute = AppOportunidadesRouteImport.update({
  id: '/oportunidades',
  path: '/oportunidades',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizacaoRoute = AppOrganizacaoRouteImport.update({
  id: '/organizacao',
  path: '/organizacao',
  getParentRoute: () => AppRoute,
} as any)
const AppOrquestracaoRoute = AppOrquestracaoRouteImport.update({
  id: '/orquestracao',
  path: '/orquestracao',
  getParentRoute: () => AppRoute,
} as any)
const AppPermissoesRoute = AppPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppPilotoRoute = AppPilotoRouteImport.update({
  id: '/piloto',
  path: '/piloto',
  getParentRoute: () => AppRoute,
} as any)
const AppPlatformRoute = AppPlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => AppRoute,
} as any)
const AppPortalClienteRoute = AppPortalClienteRouteImport.update({
  id: '/portal-cliente',
  path: '/portal-cliente',
  getParentRoute: () => AppRoute,
} as any)
const AppRadarRoute = AppRadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => AppRoute,
} as any)
const AppRelatoriosRoute = AppRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AppRoute,
} as any)
const AppTelemetriaRoute = AppTelemetriaRouteImport.update({
  id: '/telemetria',
  path: '/telemetria',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ConstrutorasCuryRoute = ConstrutorasCuryRouteImport.update({
  id: '/construtoras/cury',
  path: '/construtoras/cury',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosIndexRoute = EmpreendimentosIndexRouteImport.update({
  id: '/empreendimentos/',
  path: '/empreendimentos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosIdRoute = EmpreendimentosIdRouteImport.update({
  id: '/empreendimentos/$id',
  path: '/empreendimentos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpreendimentosCuryRoute = EmpreendimentosCuryRouteImport.update({
  id: '/empreendimentos/cury',
  path: '/empreendimentos/cury',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSplatRoute = EnSplatRouteImport.update({
  id: '/en/$',
  path: '/en/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EsSplatRoute = EsSplatRouteImport.update({
  id: '/es/$',
  path: '/es/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LpSlugRoute = LpSlugRouteImport.update({
  id: '/lp/$slug',
  path: '/lp/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHealthRoute = AppAdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppEmpreendimentosIndexRoute = AppEmpreendimentosIndexRouteImport.update({
  id: '/empreendimentos/',
  path: '/empreendimentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasIndexRoute = AppPessoasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPessoasRoute,
} as any)
const AppPessoasIdRoute = AppPessoasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppPessoasRoute,
} as any)
const EmpreendimentosCuryIndexRoute =
  EmpreendimentosCuryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmpreendimentosCuryRoute,
  } as any)
const EmpreendimentosCurySlugRoute = EmpreendimentosCurySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EmpreendimentosCuryRoute,
} as any)
const EmpreendimentosCuryCompararRoute =
  EmpreendimentosCuryCompararRouteImport.update({
    id: '/comparar',
    path: '/comparar',
    getParentRoute: () => EmpreendimentosCuryRoute,
  } as any)
const EmpreendimentosCuryMapaRoute = EmpreendimentosCuryMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => EmpreendimentosCuryRoute,
} as any)
const ApiPublicHooksAdvisorWatchdogRoute =
  ApiPublicHooksAdvisorWatchdogRouteImport.update({
    id: '/api/public/hooks/advisor-watchdog',
    path: '/api/public/hooks/advisor-watchdog',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationRollupRoute =
  ApiPublicHooksAutomationRollupRouteImport.update({
    id: '/api/public/hooks/automation-rollup',
    path: '/api/public/hooks/automation-rollup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMarketCollectorRoute =
  ApiPublicHooksMarketCollectorRouteImport.update({
    id: '/api/public/hooks/market-collector',
    path: '/api/public/hooks/market-collector',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOutboxWorkerRoute =
  ApiPublicHooksOutboxWorkerRouteImport.update({
    id: '/api/public/hooks/outbox-worker',
    path: '/api/public/hooks/outbox-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEmpreendimentosIdPropertyRoute =
  AppEmpreendimentosIdPropertyRouteImport.update({
    id: '/empreendimentos/$id/property',
    path: '/empreendimentos/$id/property',
    getParentRoute: () => AppRoute,
  } as any)
const AppEmpreendimentosIdUnidadesRoute =
  AppEmpreendimentosIdUnidadesRouteImport.update({
    id: '/empreendimentos/$id/unidades',
    path: '/empreendimentos/$id/unidades',
    getParentRoute: () => AppRoute,
  } as any)
const EmpreendimentosCurySlugIndexRoute =
  EmpreendimentosCurySlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EmpreendimentosCurySlugRoute,
  } as any)
const EmpreendimentosCurySlugLandingRoute =
  EmpreendimentosCurySlugLandingRouteImport.update({
    id: '/landing',
    path: '/landing',
    getParentRoute: () => EmpreendimentosCurySlugRoute,
  } as any)
const EmpreendimentosCurySlugUnidadeUnidadeIdRoute =
  EmpreendimentosCurySlugUnidadeUnidadeIdRouteImport.update({
    id: '/unidade/$unidadeId',
    path: '/unidade/$unidadeId',
    getParentRoute: () => EmpreendimentosCurySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/carreiras': typeof CarreirasRoute
  '/contato': typeof ContatoRoute
  '/design-system': typeof DesignSystemRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/simulacao': typeof SimulacaoRoute
  '/sitemap-imagens.xml': typeof SitemapImagensDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/advisor': typeof AppAdvisorRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/ativos': typeof AppAtivosRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comportamento': typeof AppComportamentoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/construtoras': typeof AppConstrutorasRoute
  '/app/conteudos': typeof AppConteudosRoute
  '/app/corretores': typeof AppCorretoresRoute
  '/app/crm': typeof AppCrmRoute
  '/app/decisoes': typeof AppDecisoesRoute
  '/app/ecossistema': typeof AppEcossistemaRoute
  '/app/equipes': typeof AppEquipesRoute
  '/app/erp': typeof AppErpRoute
  '/app/executive': typeof AppExecutiveRoute
  '/app/fabric': typeof AppFabricRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/funis': typeof AppFunisRoute
  '/app/gonogo': typeof AppGonogoRoute
  '/app/ia': typeof AppIaRoute
  '/app/importar': typeof AppImportarRoute
  '/app/institucional': typeof AppInstitucionalRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/landing': typeof AppLandingRoute
  '/app/leads-site': typeof AppLeadsSiteRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/memoria': typeof AppMemoriaRoute
  '/app/mercado': typeof AppMercadoRoute
  '/app/midia': typeof AppMidiaRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/organizacao': typeof AppOrganizacaoRoute
  '/app/orquestracao': typeof AppOrquestracaoRoute
  '/app/permissoes': typeof AppPermissoesRoute
  '/app/pessoas': typeof AppPessoasRouteWithChildren
  '/app/piloto': typeof AppPilotoRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/portal-cliente': typeof AppPortalClienteRoute
  '/app/radar': typeof AppRadarRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/telemetria': typeof AppTelemetriaRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/construtoras/cury': typeof ConstrutorasCuryRoute
  '/empreendimentos/$id': typeof EmpreendimentosIdRoute
  '/empreendimentos/cury': typeof EmpreendimentosCuryRouteWithChildren
  '/en/$': typeof EnSplatRoute
  '/es/$': typeof EsSplatRoute
  '/lp/$slug': typeof LpSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/empreendimentos/': typeof EmpreendimentosIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/admin/health': typeof AppAdminHealthRoute
  '/app/pessoas/$id': typeof AppPessoasIdRoute
  '/empreendimentos/cury/$slug': typeof EmpreendimentosCurySlugRouteWithChildren
  '/empreendimentos/cury/comparar': typeof EmpreendimentosCuryCompararRoute
  '/empreendimentos/cury/mapa': typeof EmpreendimentosCuryMapaRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/empreendimentos/': typeof AppEmpreendimentosIndexRoute
  '/app/pessoas/': typeof AppPessoasIndexRoute
  '/empreendimentos/cury/': typeof EmpreendimentosCuryIndexRoute
  '/api/public/hooks/advisor-watchdog': typeof ApiPublicHooksAdvisorWatchdogRoute
  '/api/public/hooks/automation-rollup': typeof ApiPublicHooksAutomationRollupRoute
  '/api/public/hooks/market-collector': typeof ApiPublicHooksMarketCollectorRoute
  '/api/public/hooks/outbox-worker': typeof ApiPublicHooksOutboxWorkerRoute
  '/app/empreendimentos/$id/property': typeof AppEmpreendimentosIdPropertyRoute
  '/app/empreendimentos/$id/unidades': typeof AppEmpreendimentosIdUnidadesRoute
  '/empreendimentos/cury/$slug/landing': typeof EmpreendimentosCurySlugLandingRoute
  '/empreendimentos/cury/$slug/': typeof EmpreendimentosCurySlugIndexRoute
  '/empreendimentos/cury/$slug/unidade/$unidadeId': typeof EmpreendimentosCurySlugUnidadeUnidadeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/auth': typeof AuthRoute
  '/carreiras': typeof CarreirasRoute
  '/contato': typeof ContatoRoute
  '/design-system': typeof DesignSystemRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/simulacao': typeof SimulacaoRoute
  '/sitemap-imagens.xml': typeof SitemapImagensDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/advisor': typeof AppAdvisorRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/ativos': typeof AppAtivosRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comportamento': typeof AppComportamentoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/construtoras': typeof AppConstrutorasRoute
  '/app/conteudos': typeof AppConteudosRoute
  '/app/corretores': typeof AppCorretoresRoute
  '/app/crm': typeof AppCrmRoute
  '/app/decisoes': typeof AppDecisoesRoute
  '/app/ecossistema': typeof AppEcossistemaRoute
  '/app/equipes': typeof AppEquipesRoute
  '/app/erp': typeof AppErpRoute
  '/app/executive': typeof AppExecutiveRoute
  '/app/fabric': typeof AppFabricRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/funis': typeof AppFunisRoute
  '/app/gonogo': typeof AppGonogoRoute
  '/app/ia': typeof AppIaRoute
  '/app/importar': typeof AppImportarRoute
  '/app/institucional': typeof AppInstitucionalRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/landing': typeof AppLandingRoute
  '/app/leads-site': typeof AppLeadsSiteRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/memoria': typeof AppMemoriaRoute
  '/app/mercado': typeof AppMercadoRoute
  '/app/midia': typeof AppMidiaRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/organizacao': typeof AppOrganizacaoRoute
  '/app/orquestracao': typeof AppOrquestracaoRoute
  '/app/permissoes': typeof AppPermissoesRoute
  '/app/piloto': typeof AppPilotoRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/portal-cliente': typeof AppPortalClienteRoute
  '/app/radar': typeof AppRadarRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/telemetria': typeof AppTelemetriaRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/construtoras/cury': typeof ConstrutorasCuryRoute
  '/empreendimentos/$id': typeof EmpreendimentosIdRoute
  '/en/$': typeof EnSplatRoute
  '/es/$': typeof EsSplatRoute
  '/lp/$slug': typeof LpSlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
  '/empreendimentos': typeof EmpreendimentosIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/admin/health': typeof AppAdminHealthRoute
  '/app/pessoas/$id': typeof AppPessoasIdRoute
  '/empreendimentos/cury/comparar': typeof EmpreendimentosCuryCompararRoute
  '/empreendimentos/cury/mapa': typeof EmpreendimentosCuryMapaRoute
  '/app/admin': typeof AppAdminIndexRoute
  '/app/empreendimentos': typeof AppEmpreendimentosIndexRoute
  '/app/pessoas': typeof AppPessoasIndexRoute
  '/empreendimentos/cury': typeof EmpreendimentosCuryIndexRoute
  '/api/public/hooks/advisor-watchdog': typeof ApiPublicHooksAdvisorWatchdogRoute
  '/api/public/hooks/automation-rollup': typeof ApiPublicHooksAutomationRollupRoute
  '/api/public/hooks/market-collector': typeof ApiPublicHooksMarketCollectorRoute
  '/api/public/hooks/outbox-worker': typeof ApiPublicHooksOutboxWorkerRoute
  '/app/empreendimentos/$id/property': typeof AppEmpreendimentosIdPropertyRoute
  '/app/empreendimentos/$id/unidades': typeof AppEmpreendimentosIdUnidadesRoute
  '/empreendimentos/cury/$slug/landing': typeof EmpreendimentosCurySlugLandingRoute
  '/empreendimentos/cury/$slug': typeof EmpreendimentosCurySlugIndexRoute
  '/empreendimentos/cury/$slug/unidade/$unidadeId': typeof EmpreendimentosCurySlugUnidadeUnidadeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/carreiras': typeof CarreirasRoute
  '/contato': typeof ContatoRoute
  '/design-system': typeof DesignSystemRoute
  '/manifest.json': typeof ManifestDotjsonRoute
  '/manifesto': typeof ManifestoRoute
  '/metodo': typeof MetodoRoute
  '/onboarding': typeof OnboardingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/simulacao': typeof SimulacaoRoute
  '/sitemap-imagens.xml': typeof SitemapImagensDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/app/academy': typeof AppAcademyRoute
  '/app/admin': typeof AppAdminRouteWithChildren
  '/app/advisor': typeof AppAdvisorRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/ativos': typeof AppAtivosRoute
  '/app/auditoria': typeof AppAuditoriaRoute
  '/app/automacoes': typeof AppAutomacoesRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/clientes': typeof AppClientesRoute
  '/app/comportamento': typeof AppComportamentoRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/construtoras': typeof AppConstrutorasRoute
  '/app/conteudos': typeof AppConteudosRoute
  '/app/corretores': typeof AppCorretoresRoute
  '/app/crm': typeof AppCrmRoute
  '/app/decisoes': typeof AppDecisoesRoute
  '/app/ecossistema': typeof AppEcossistemaRoute
  '/app/equipes': typeof AppEquipesRoute
  '/app/erp': typeof AppErpRoute
  '/app/executive': typeof AppExecutiveRoute
  '/app/fabric': typeof AppFabricRoute
  '/app/feedback': typeof AppFeedbackRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/funis': typeof AppFunisRoute
  '/app/gonogo': typeof AppGonogoRoute
  '/app/ia': typeof AppIaRoute
  '/app/importar': typeof AppImportarRoute
  '/app/institucional': typeof AppInstitucionalRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/landing': typeof AppLandingRoute
  '/app/leads-site': typeof AppLeadsSiteRoute
  '/app/marketing': typeof AppMarketingRoute
  '/app/memoria': typeof AppMemoriaRoute
  '/app/mercado': typeof AppMercadoRoute
  '/app/midia': typeof AppMidiaRoute
  '/app/oportunidades': typeof AppOportunidadesRoute
  '/app/organizacao': typeof AppOrganizacaoRoute
  '/app/orquestracao': typeof AppOrquestracaoRoute
  '/app/permissoes': typeof AppPermissoesRoute
  '/app/pessoas': typeof AppPessoasRouteWithChildren
  '/app/piloto': typeof AppPilotoRoute
  '/app/platform': typeof AppPlatformRoute
  '/app/portal-cliente': typeof AppPortalClienteRoute
  '/app/radar': typeof AppRadarRoute
  '/app/relatorios': typeof AppRelatoriosRoute
  '/app/telemetria': typeof AppTelemetriaRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/construtoras/cury': typeof ConstrutorasCuryRoute
  '/empreendimentos/$id': typeof EmpreendimentosIdRoute
  '/empreendimentos/cury': typeof EmpreendimentosCuryRouteWithChildren
  '/en/$': typeof EnSplatRoute
  '/es/$': typeof EsSplatRoute
  '/lp/$slug': typeof LpSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/empreendimentos/': typeof EmpreendimentosIndexRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/app/admin/health': typeof AppAdminHealthRoute
  '/app/pessoas/$id': typeof AppPessoasIdRoute
  '/empreendimentos/cury/$slug': typeof EmpreendimentosCurySlugRouteWithChildren
  '/empreendimentos/cury/comparar': typeof EmpreendimentosCuryCompararRoute
  '/empreendimentos/cury/mapa': typeof EmpreendimentosCuryMapaRoute
  '/app/admin/': typeof AppAdminIndexRoute
  '/app/empreendimentos/': typeof AppEmpreendimentosIndexRoute
  '/app/pessoas/': typeof AppPessoasIndexRoute
  '/empreendimentos/cury/': typeof EmpreendimentosCuryIndexRoute
  '/api/public/hooks/advisor-watchdog': typeof ApiPublicHooksAdvisorWatchdogRoute
  '/api/public/hooks/automation-rollup': typeof ApiPublicHooksAutomationRollupRoute
  '/api/public/hooks/market-collector': typeof ApiPublicHooksMarketCollectorRoute
  '/api/public/hooks/outbox-worker': typeof ApiPublicHooksOutboxWorkerRoute
  '/app/empreendimentos/$id/property': typeof AppEmpreendimentosIdPropertyRoute
  '/app/empreendimentos/$id/unidades': typeof AppEmpreendimentosIdUnidadesRoute
  '/empreendimentos/cury/$slug/landing': typeof EmpreendimentosCurySlugLandingRoute
  '/empreendimentos/cury/$slug/': typeof EmpreendimentosCurySlugIndexRoute
  '/empreendimentos/cury/$slug/unidade/$unidadeId': typeof EmpreendimentosCurySlugUnidadeUnidadeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/app'
    | '/auth'
    | '/blog'
    | '/carreiras'
    | '/contato'
    | '/design-system'
    | '/manifest.json'
    | '/manifesto'
    | '/metodo'
    | '/onboarding'
    | '/robots.txt'
    | '/simulacao'
    | '/sitemap-imagens.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/app/academy'
    | '/app/admin'
    | '/app/advisor'
    | '/app/agenda'
    | '/app/analytics'
    | '/app/ativos'
    | '/app/auditoria'
    | '/app/automacoes'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/comportamento'
    | '/app/configuracoes'
    | '/app/construtoras'
    | '/app/conteudos'
    | '/app/corretores'
    | '/app/crm'
    | '/app/decisoes'
    | '/app/ecossistema'
    | '/app/equipes'
    | '/app/erp'
    | '/app/executive'
    | '/app/fabric'
    | '/app/feedback'
    | '/app/financeiro'
    | '/app/funis'
    | '/app/gonogo'
    | '/app/ia'
    | '/app/importar'
    | '/app/institucional'
    | '/app/knowledge'
    | '/app/landing'
    | '/app/leads-site'
    | '/app/marketing'
    | '/app/memoria'
    | '/app/mercado'
    | '/app/midia'
    | '/app/oportunidades'
    | '/app/organizacao'
    | '/app/orquestracao'
    | '/app/permissoes'
    | '/app/pessoas'
    | '/app/piloto'
    | '/app/platform'
    | '/app/portal-cliente'
    | '/app/radar'
    | '/app/relatorios'
    | '/app/telemetria'
    | '/app/usuarios'
    | '/blog/$slug'
    | '/construtoras/cury'
    | '/empreendimentos/$id'
    | '/empreendimentos/cury'
    | '/en/$'
    | '/es/$'
    | '/lp/$slug'
    | '/app/'
    | '/blog/'
    | '/empreendimentos/'
    | '/api/public/health'
    | '/app/admin/health'
    | '/app/pessoas/$id'
    | '/empreendimentos/cury/$slug'
    | '/empreendimentos/cury/comparar'
    | '/empreendimentos/cury/mapa'
    | '/app/admin/'
    | '/app/empreendimentos/'
    | '/app/pessoas/'
    | '/empreendimentos/cury/'
    | '/api/public/hooks/advisor-watchdog'
    | '/api/public/hooks/automation-rollup'
    | '/api/public/hooks/market-collector'
    | '/api/public/hooks/outbox-worker'
    | '/app/empreendimentos/$id/property'
    | '/app/empreendimentos/$id/unidades'
    | '/empreendimentos/cury/$slug/landing'
    | '/empreendimentos/cury/$slug/'
    | '/empreendimentos/cury/$slug/unidade/$unidadeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/auth'
    | '/carreiras'
    | '/contato'
    | '/design-system'
    | '/manifest.json'
    | '/manifesto'
    | '/metodo'
    | '/onboarding'
    | '/robots.txt'
    | '/simulacao'
    | '/sitemap-imagens.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/app/academy'
    | '/app/advisor'
    | '/app/agenda'
    | '/app/analytics'
    | '/app/ativos'
    | '/app/auditoria'
    | '/app/automacoes'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/comportamento'
    | '/app/configuracoes'
    | '/app/construtoras'
    | '/app/conteudos'
    | '/app/corretores'
    | '/app/crm'
    | '/app/decisoes'
    | '/app/ecossistema'
    | '/app/equipes'
    | '/app/erp'
    | '/app/executive'
    | '/app/fabric'
    | '/app/feedback'
    | '/app/financeiro'
    | '/app/funis'
    | '/app/gonogo'
    | '/app/ia'
    | '/app/importar'
    | '/app/institucional'
    | '/app/knowledge'
    | '/app/landing'
    | '/app/leads-site'
    | '/app/marketing'
    | '/app/memoria'
    | '/app/mercado'
    | '/app/midia'
    | '/app/oportunidades'
    | '/app/organizacao'
    | '/app/orquestracao'
    | '/app/permissoes'
    | '/app/piloto'
    | '/app/platform'
    | '/app/portal-cliente'
    | '/app/radar'
    | '/app/relatorios'
    | '/app/telemetria'
    | '/app/usuarios'
    | '/blog/$slug'
    | '/construtoras/cury'
    | '/empreendimentos/$id'
    | '/en/$'
    | '/es/$'
    | '/lp/$slug'
    | '/app'
    | '/blog'
    | '/empreendimentos'
    | '/api/public/health'
    | '/app/admin/health'
    | '/app/pessoas/$id'
    | '/empreendimentos/cury/comparar'
    | '/empreendimentos/cury/mapa'
    | '/app/admin'
    | '/app/empreendimentos'
    | '/app/pessoas'
    | '/empreendimentos/cury'
    | '/api/public/hooks/advisor-watchdog'
    | '/api/public/hooks/automation-rollup'
    | '/api/public/hooks/market-collector'
    | '/api/public/hooks/outbox-worker'
    | '/app/empreendimentos/$id/property'
    | '/app/empreendimentos/$id/unidades'
    | '/empreendimentos/cury/$slug/landing'
    | '/empreendimentos/cury/$slug'
    | '/empreendimentos/cury/$slug/unidade/$unidadeId'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/app'
    | '/auth'
    | '/blog'
    | '/carreiras'
    | '/contato'
    | '/design-system'
    | '/manifest.json'
    | '/manifesto'
    | '/metodo'
    | '/onboarding'
    | '/robots.txt'
    | '/simulacao'
    | '/sitemap-imagens.xml'
    | '/sitemap.xml'
    | '/sobre'
    | '/app/academy'
    | '/app/admin'
    | '/app/advisor'
    | '/app/agenda'
    | '/app/analytics'
    | '/app/ativos'
    | '/app/auditoria'
    | '/app/automacoes'
    | '/app/campanhas'
    | '/app/clientes'
    | '/app/comportamento'
    | '/app/configuracoes'
    | '/app/construtoras'
    | '/app/conteudos'
    | '/app/corretores'
    | '/app/crm'
    | '/app/decisoes'
    | '/app/ecossistema'
    | '/app/equipes'
    | '/app/erp'
    | '/app/executive'
    | '/app/fabric'
    | '/app/feedback'
    | '/app/financeiro'
    | '/app/funis'
    | '/app/gonogo'
    | '/app/ia'
    | '/app/importar'
    | '/app/institucional'
    | '/app/knowledge'
    | '/app/landing'
    | '/app/leads-site'
    | '/app/marketing'
    | '/app/memoria'
    | '/app/mercado'
    | '/app/midia'
    | '/app/oportunidades'
    | '/app/organizacao'
    | '/app/orquestracao'
    | '/app/permissoes'
    | '/app/pessoas'
    | '/app/piloto'
    | '/app/platform'
    | '/app/portal-cliente'
    | '/app/radar'
    | '/app/relatorios'
    | '/app/telemetria'
    | '/app/usuarios'
    | '/blog/$slug'
    | '/construtoras/cury'
    | '/empreendimentos/$id'
    | '/empreendimentos/cury'
    | '/en/$'
    | '/es/$'
    | '/lp/$slug'
    | '/app/'
    | '/blog/'
    | '/empreendimentos/'
    | '/api/public/health'
    | '/app/admin/health'
    | '/app/pessoas/$id'
    | '/empreendimentos/cury/$slug'
    | '/empreendimentos/cury/comparar'
    | '/empreendimentos/cury/mapa'
    | '/app/admin/'
    | '/app/empreendimentos/'
    | '/app/pessoas/'
    | '/empreendimentos/cury/'
    | '/api/public/hooks/advisor-watchdog'
    | '/api/public/hooks/automation-rollup'
    | '/api/public/hooks/market-collector'
    | '/api/public/hooks/outbox-worker'
    | '/app/empreendimentos/$id/property'
    | '/app/empreendimentos/$id/unidades'
    | '/empreendimentos/cury/$slug/landing'
    | '/empreendimentos/cury/$slug/'
    | '/empreendimentos/cury/$slug/unidade/$unidadeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CarreirasRoute: typeof CarreirasRoute
  ContatoRoute: typeof ContatoRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ManifestDotjsonRoute: typeof ManifestDotjsonRoute
  ManifestoRoute: typeof ManifestoRoute
  MetodoRoute: typeof MetodoRoute
  OnboardingRoute: typeof OnboardingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SimulacaoRoute: typeof SimulacaoRoute
  SitemapImagensDotxmlRoute: typeof SitemapImagensDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ConstrutorasCuryRoute: typeof ConstrutorasCuryRoute
  EmpreendimentosIdRoute: typeof EmpreendimentosIdRoute
  EmpreendimentosCuryRoute: typeof EmpreendimentosCuryRouteWithChildren
  EnSplatRoute: typeof EnSplatRoute
  EsSplatRoute: typeof EsSplatRoute
  LpSlugRoute: typeof LpSlugRoute
  EmpreendimentosIndexRoute: typeof EmpreendimentosIndexRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksAdvisorWatchdogRoute: typeof ApiPublicHooksAdvisorWatchdogRoute
  ApiPublicHooksAutomationRollupRoute: typeof ApiPublicHooksAutomationRollupRoute
  ApiPublicHooksMarketCollectorRoute: typeof ApiPublicHooksMarketCollectorRoute
  ApiPublicHooksOutboxWorkerRoute: typeof ApiPublicHooksOutboxWorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras': {
      id: '/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof CarreirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.json': {
      id: '/manifest.json'
      path: '/manifest.json'
      fullPath: '/manifest.json'
      preLoaderRoute: typeof ManifestDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo': {
      id: '/metodo'
      path: '/metodo'
      fullPath: '/metodo'
      preLoaderRoute: typeof MetodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-imagens.xml': {
      id: '/sitemap-imagens.xml'
      path: '/sitemap-imagens.xml'
      fullPath: '/sitemap-imagens.xml'
      preLoaderRoute: typeof SitemapImagensDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/academy': {
      id: '/app/academy'
      path: '/academy'
      fullPath: '/app/academy'
      preLoaderRoute: typeof AppAcademyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/advisor': {
      id: '/app/advisor'
      path: '/advisor'
      fullPath: '/app/advisor'
      preLoaderRoute: typeof AppAdvisorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ativos': {
      id: '/app/ativos'
      path: '/ativos'
      fullPath: '/app/ativos'
      preLoaderRoute: typeof AppAtivosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/auditoria': {
      id: '/app/auditoria'
      path: '/auditoria'
      fullPath: '/app/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automacoes': {
      id: '/app/automacoes'
      path: '/automacoes'
      fullPath: '/app/automacoes'
      preLoaderRoute: typeof AppAutomacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/clientes': {
      id: '/app/clientes'
      path: '/clientes'
      fullPath: '/app/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comportamento': {
      id: '/app/comportamento'
      path: '/comportamento'
      fullPath: '/app/comportamento'
      preLoaderRoute: typeof AppComportamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/construtoras': {
      id: '/app/construtoras'
      path: '/construtoras'
      fullPath: '/app/construtoras'
      preLoaderRoute: typeof AppConstrutorasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conteudos': {
      id: '/app/conteudos'
      path: '/conteudos'
      fullPath: '/app/conteudos'
      preLoaderRoute: typeof AppConteudosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/corretores': {
      id: '/app/corretores'
      path: '/corretores'
      fullPath: '/app/corretores'
      preLoaderRoute: typeof AppCorretoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/decisoes': {
      id: '/app/decisoes'
      path: '/decisoes'
      fullPath: '/app/decisoes'
      preLoaderRoute: typeof AppDecisoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ecossistema': {
      id: '/app/ecossistema'
      path: '/ecossistema'
      fullPath: '/app/ecossistema'
      preLoaderRoute: typeof AppEcossistemaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipes': {
      id: '/app/equipes'
      path: '/equipes'
      fullPath: '/app/equipes'
      preLoaderRoute: typeof AppEquipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/erp': {
      id: '/app/erp'
      path: '/erp'
      fullPath: '/app/erp'
      preLoaderRoute: typeof AppErpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/executive': {
      id: '/app/executive'
      path: '/executive'
      fullPath: '/app/executive'
      preLoaderRoute: typeof AppExecutiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fabric': {
      id: '/app/fabric'
      path: '/fabric'
      fullPath: '/app/fabric'
      preLoaderRoute: typeof AppFabricRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/feedback': {
      id: '/app/feedback'
      path: '/feedback'
      fullPath: '/app/feedback'
      preLoaderRoute: typeof AppFeedbackRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/funis': {
      id: '/app/funis'
      path: '/funis'
      fullPath: '/app/funis'
      preLoaderRoute: typeof AppFunisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/gonogo': {
      id: '/app/gonogo'
      path: '/gonogo'
      fullPath: '/app/gonogo'
      preLoaderRoute: typeof AppGonogoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ia': {
      id: '/app/ia'
      path: '/ia'
      fullPath: '/app/ia'
      preLoaderRoute: typeof AppIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importar': {
      id: '/app/importar'
      path: '/importar'
      fullPath: '/app/importar'
      preLoaderRoute: typeof AppImportarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/institucional': {
      id: '/app/institucional'
      path: '/institucional'
      fullPath: '/app/institucional'
      preLoaderRoute: typeof AppInstitucionalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/landing': {
      id: '/app/landing'
      path: '/landing'
      fullPath: '/app/landing'
      preLoaderRoute: typeof AppLandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads-site': {
      id: '/app/leads-site'
      path: '/leads-site'
      fullPath: '/app/leads-site'
      preLoaderRoute: typeof AppLeadsSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/marketing': {
      id: '/app/marketing'
      path: '/marketing'
      fullPath: '/app/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/memoria': {
      id: '/app/memoria'
      path: '/memoria'
      fullPath: '/app/memoria'
      preLoaderRoute: typeof AppMemoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mercado': {
      id: '/app/mercado'
      path: '/mercado'
      fullPath: '/app/mercado'
      preLoaderRoute: typeof AppMercadoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/midia': {
      id: '/app/midia'
      path: '/midia'
      fullPath: '/app/midia'
      preLoaderRoute: typeof AppMidiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/oportunidades': {
      id: '/app/oportunidades'
      path: '/oportunidades'
      fullPath: '/app/oportunidades'
      preLoaderRoute: typeof AppOportunidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizacao': {
      id: '/app/organizacao'
      path: '/organizacao'
      fullPath: '/app/organizacao'
      preLoaderRoute: typeof AppOrganizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orquestracao': {
      id: '/app/orquestracao'
      path: '/orquestracao'
      fullPath: '/app/orquestracao'
      preLoaderRoute: typeof AppOrquestracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/permissoes': {
      id: '/app/permissoes'
      path: '/permissoes'
      fullPath: '/app/permissoes'
      preLoaderRoute: typeof AppPermissoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas': {
      id: '/app/pessoas'
      path: '/pessoas'
      fullPath: '/app/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/piloto': {
      id: '/app/piloto'
      path: '/piloto'
      fullPath: '/app/piloto'
      preLoaderRoute: typeof AppPilotoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/platform': {
      id: '/app/platform'
      path: '/platform'
      fullPath: '/app/platform'
      preLoaderRoute: typeof AppPlatformRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portal-cliente': {
      id: '/app/portal-cliente'
      path: '/portal-cliente'
      fullPath: '/app/portal-cliente'
      preLoaderRoute: typeof AppPortalClienteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/radar': {
      id: '/app/radar'
      path: '/radar'
      fullPath: '/app/radar'
      preLoaderRoute: typeof AppRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/relatorios': {
      id: '/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AppRelatoriosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/telemetria': {
      id: '/app/telemetria'
      path: '/telemetria'
      fullPath: '/app/telemetria'
      preLoaderRoute: typeof AppTelemetriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/construtoras/cury': {
      id: '/construtoras/cury'
      path: '/construtoras/cury'
      fullPath: '/construtoras/cury'
      preLoaderRoute: typeof ConstrutorasCuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/': {
      id: '/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/empreendimentos/'
      preLoaderRoute: typeof EmpreendimentosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/$id': {
      id: '/empreendimentos/$id'
      path: '/empreendimentos/$id'
      fullPath: '/empreendimentos/$id'
      preLoaderRoute: typeof EmpreendimentosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empreendimentos/cury': {
      id: '/empreendimentos/cury'
      path: '/empreendimentos/cury'
      fullPath: '/empreendimentos/cury'
      preLoaderRoute: typeof EmpreendimentosCuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/$': {
      id: '/en/$'
      path: '/en/$'
      fullPath: '/en/$'
      preLoaderRoute: typeof EnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/es/$': {
      id: '/es/$'
      path: '/es/$'
      fullPath: '/es/$'
      preLoaderRoute: typeof EsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$slug': {
      id: '/lp/$slug'
      path: '/lp/$slug'
      fullPath: '/lp/$slug'
      preLoaderRoute: typeof LpSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/': {
      id: '/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/admin/health': {
      id: '/app/admin/health'
      path: '/health'
      fullPath: '/app/admin/health'
      preLoaderRoute: typeof AppAdminHealthRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/app/empreendimentos/': {
      id: '/app/empreendimentos/'
      path: '/empreendimentos'
      fullPath: '/app/empreendimentos/'
      preLoaderRoute: typeof AppEmpreendimentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas/': {
      id: '/app/pessoas/'
      path: '/'
      fullPath: '/app/pessoas/'
      preLoaderRoute: typeof AppPessoasIndexRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/app/pessoas/$id': {
      id: '/app/pessoas/$id'
      path: '/$id'
      fullPath: '/app/pessoas/$id'
      preLoaderRoute: typeof AppPessoasIdRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/empreendimentos/cury/': {
      id: '/empreendimentos/cury/'
      path: '/'
      fullPath: '/empreendimentos/cury/'
      preLoaderRoute: typeof EmpreendimentosCuryIndexRouteImport
      parentRoute: typeof EmpreendimentosCuryRoute
    }
    '/empreendimentos/cury/$slug': {
      id: '/empreendimentos/cury/$slug'
      path: '/$slug'
      fullPath: '/empreendimentos/cury/$slug'
      preLoaderRoute: typeof EmpreendimentosCurySlugRouteImport
      parentRoute: typeof EmpreendimentosCuryRoute
    }
    '/empreendimentos/cury/comparar': {
      id: '/empreendimentos/cury/comparar'
      path: '/comparar'
      fullPath: '/empreendimentos/cury/comparar'
      preLoaderRoute: typeof EmpreendimentosCuryCompararRouteImport
      parentRoute: typeof EmpreendimentosCuryRoute
    }
    '/empreendimentos/cury/mapa': {
      id: '/empreendimentos/cury/mapa'
      path: '/mapa'
      fullPath: '/empreendimentos/cury/mapa'
      preLoaderRoute: typeof EmpreendimentosCuryMapaRouteImport
      parentRoute: typeof EmpreendimentosCuryRoute
    }
    '/api/public/hooks/advisor-watchdog': {
      id: '/api/public/hooks/advisor-watchdog'
      path: '/api/public/hooks/advisor-watchdog'
      fullPath: '/api/public/hooks/advisor-watchdog'
      preLoaderRoute: typeof ApiPublicHooksAdvisorWatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-rollup': {
      id: '/api/public/hooks/automation-rollup'
      path: '/api/public/hooks/automation-rollup'
      fullPath: '/api/public/hooks/automation-rollup'
      preLoaderRoute: typeof ApiPublicHooksAutomationRollupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/market-collector': {
      id: '/api/public/hooks/market-collector'
      path: '/api/public/hooks/market-collector'
      fullPath: '/api/public/hooks/market-collector'
      preLoaderRoute: typeof ApiPublicHooksMarketCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/outbox-worker': {
      id: '/api/public/hooks/outbox-worker'
      path: '/api/public/hooks/outbox-worker'
      fullPath: '/api/public/hooks/outbox-worker'
      preLoaderRoute: typeof ApiPublicHooksOutboxWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/empreendimentos/$id/property': {
      id: '/app/empreendimentos/$id/property'
      path: '/empreendimentos/$id/property'
      fullPath: '/app/empreendimentos/$id/property'
      preLoaderRoute: typeof AppEmpreendimentosIdPropertyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/empreendimentos/$id/unidades': {
      id: '/app/empreendimentos/$id/unidades'
      path: '/empreendimentos/$id/unidades'
      fullPath: '/app/empreendimentos/$id/unidades'
      preLoaderRoute: typeof AppEmpreendimentosIdUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/empreendimentos/cury/$slug/': {
      id: '/empreendimentos/cury/$slug/'
      path: '/'
      fullPath: '/empreendimentos/cury/$slug/'
      preLoaderRoute: typeof EmpreendimentosCurySlugIndexRouteImport
      parentRoute: typeof EmpreendimentosCurySlugRoute
    }
    '/empreendimentos/cury/$slug/landing': {
      id: '/empreendimentos/cury/$slug/landing'
      path: '/landing'
      fullPath: '/empreendimentos/cury/$slug/landing'
      preLoaderRoute: typeof EmpreendimentosCurySlugLandingRouteImport
      parentRoute: typeof EmpreendimentosCurySlugRoute
    }
    '/empreendimentos/cury/$slug/unidade/$unidadeId': {
      id: '/empreendimentos/cury/$slug/unidade/$unidadeId'
      path: '/unidade/$unidadeId'
      fullPath: '/empreendimentos/cury/$slug/unidade/$unidadeId'
      preLoaderRoute: typeof EmpreendimentosCurySlugUnidadeUnidadeIdRouteImport
      parentRoute: typeof EmpreendimentosCurySlugRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminHealthRoute: typeof AppAdminHealthRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminHealthRoute: AppAdminHealthRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppPessoasRouteChildren {
  AppPessoasIdRoute: typeof AppPessoasIdRoute
  AppPessoasIndexRoute: typeof AppPessoasIndexRoute
}

const AppPessoasRouteChildren: AppPessoasRouteChildren = {
  AppPessoasIdRoute: AppPessoasIdRoute,
  AppPessoasIndexRoute: AppPessoasIndexRoute,
}

const AppPessoasRouteWithChildren = AppPessoasRoute._addFileChildren(
  AppPessoasRouteChildren,
)

interface AppRouteChildren {
  AppAcademyRoute: typeof AppAcademyRoute
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppAdvisorRoute: typeof AppAdvisorRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAtivosRoute: typeof AppAtivosRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppAutomacoesRoute: typeof AppAutomacoesRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppComportamentoRoute: typeof AppComportamentoRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConstrutorasRoute: typeof AppConstrutorasRoute
  AppConteudosRoute: typeof AppConteudosRoute
  AppCorretoresRoute: typeof AppCorretoresRoute
  AppCrmRoute: typeof AppCrmRoute
  AppDecisoesRoute: typeof AppDecisoesRoute
  AppEcossistemaRoute: typeof AppEcossistemaRoute
  AppEquipesRoute: typeof AppEquipesRoute
  AppErpRoute: typeof AppErpRoute
  AppExecutiveRoute: typeof AppExecutiveRoute
  AppFabricRoute: typeof AppFabricRoute
  AppFeedbackRoute: typeof AppFeedbackRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppFunisRoute: typeof AppFunisRoute
  AppGonogoRoute: typeof AppGonogoRoute
  AppIaRoute: typeof AppIaRoute
  AppImportarRoute: typeof AppImportarRoute
  AppInstitucionalRoute: typeof AppInstitucionalRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppLandingRoute: typeof AppLandingRoute
  AppLeadsSiteRoute: typeof AppLeadsSiteRoute
  AppMarketingRoute: typeof AppMarketingRoute
  AppMemoriaRoute: typeof AppMemoriaRoute
  AppMercadoRoute: typeof AppMercadoRoute
  AppMidiaRoute: typeof AppMidiaRoute
  AppOportunidadesRoute: typeof AppOportunidadesRoute
  AppOrganizacaoRoute: typeof AppOrganizacaoRoute
  AppOrquestracaoRoute: typeof AppOrquestracaoRoute
  AppPermissoesRoute: typeof AppPermissoesRoute
  AppPessoasRoute: typeof AppPessoasRouteWithChildren
  AppPilotoRoute: typeof AppPilotoRoute
  AppPlatformRoute: typeof AppPlatformRoute
  AppPortalClienteRoute: typeof AppPortalClienteRoute
  AppRadarRoute: typeof AppRadarRoute
  AppRelatoriosRoute: typeof AppRelatoriosRoute
  AppTelemetriaRoute: typeof AppTelemetriaRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmpreendimentosIndexRoute: typeof AppEmpreendimentosIndexRoute
  AppEmpreendimentosIdPropertyRoute: typeof AppEmpreendimentosIdPropertyRoute
  AppEmpreendimentosIdUnidadesRoute: typeof AppEmpreendimentosIdUnidadesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademyRoute: AppAcademyRoute,
  AppAdminRoute: AppAdminRouteWithChildren,
  AppAdvisorRoute: AppAdvisorRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAtivosRoute: AppAtivosRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppAutomacoesRoute: AppAutomacoesRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppClientesRoute: AppClientesRoute,
  AppComportamentoRoute: AppComportamentoRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConstrutorasRoute: AppConstrutorasRoute,
  AppConteudosRoute: AppConteudosRoute,
  AppCorretoresRoute: AppCorretoresRoute,
  AppCrmRoute: AppCrmRoute,
  AppDecisoesRoute: AppDecisoesRoute,
  AppEcossistemaRoute: AppEcossistemaRoute,
  AppEquipesRoute: AppEquipesRoute,
  AppErpRoute: AppErpRoute,
  AppExecutiveRoute: AppExecutiveRoute,
  AppFabricRoute: AppFabricRoute,
  AppFeedbackRoute: AppFeedbackRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppFunisRoute: AppFunisRoute,
  AppGonogoRoute: AppGonogoRoute,
  AppIaRoute: AppIaRoute,
  AppImportarRoute: AppImportarRoute,
  AppInstitucionalRoute: AppInstitucionalRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppLandingRoute: AppLandingRoute,
  AppLeadsSiteRoute: AppLeadsSiteRoute,
  AppMarketingRoute: AppMarketingRoute,
  AppMemoriaRoute: AppMemoriaRoute,
  AppMercadoRoute: AppMercadoRoute,
  AppMidiaRoute: AppMidiaRoute,
  AppOportunidadesRoute: AppOportunidadesRoute,
  AppOrganizacaoRoute: AppOrganizacaoRoute,
  AppOrquestracaoRoute: AppOrquestracaoRoute,
  AppPermissoesRoute: AppPermissoesRoute,
  AppPessoasRoute: AppPessoasRouteWithChildren,
  AppPilotoRoute: AppPilotoRoute,
  AppPlatformRoute: AppPlatformRoute,
  AppPortalClienteRoute: AppPortalClienteRoute,
  AppRadarRoute: AppRadarRoute,
  AppRelatoriosRoute: AppRelatoriosRoute,
  AppTelemetriaRoute: AppTelemetriaRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmpreendimentosIndexRoute: AppEmpreendimentosIndexRoute,
  AppEmpreendimentosIdPropertyRoute: AppEmpreendimentosIdPropertyRoute,
  AppEmpreendimentosIdUnidadesRoute: AppEmpreendimentosIdUnidadesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface EmpreendimentosCurySlugRouteChildren {
  EmpreendimentosCurySlugLandingRoute: typeof EmpreendimentosCurySlugLandingRoute
  EmpreendimentosCurySlugIndexRoute: typeof EmpreendimentosCurySlugIndexRoute
  EmpreendimentosCurySlugUnidadeUnidadeIdRoute: typeof EmpreendimentosCurySlugUnidadeUnidadeIdRoute
}

const EmpreendimentosCurySlugRouteChildren: EmpreendimentosCurySlugRouteChildren =
  {
    EmpreendimentosCurySlugLandingRoute: EmpreendimentosCurySlugLandingRoute,
    EmpreendimentosCurySlugIndexRoute: EmpreendimentosCurySlugIndexRoute,
    EmpreendimentosCurySlugUnidadeUnidadeIdRoute:
      EmpreendimentosCurySlugUnidadeUnidadeIdRoute,
  }

const EmpreendimentosCurySlugRouteWithChildren =
  EmpreendimentosCurySlugRoute._addFileChildren(
    EmpreendimentosCurySlugRouteChildren,
  )

interface EmpreendimentosCuryRouteChildren {
  EmpreendimentosCurySlugRoute: typeof EmpreendimentosCurySlugRouteWithChildren
  EmpreendimentosCuryCompararRoute: typeof EmpreendimentosCuryCompararRoute
  EmpreendimentosCuryMapaRoute: typeof EmpreendimentosCuryMapaRoute
  EmpreendimentosCuryIndexRoute: typeof EmpreendimentosCuryIndexRoute
}

const EmpreendimentosCuryRouteChildren: EmpreendimentosCuryRouteChildren = {
  EmpreendimentosCurySlugRoute: EmpreendimentosCurySlugRouteWithChildren,
  EmpreendimentosCuryCompararRoute: EmpreendimentosCuryCompararRoute,
  EmpreendimentosCuryMapaRoute: EmpreendimentosCuryMapaRoute,
  EmpreendimentosCuryIndexRoute: EmpreendimentosCuryIndexRoute,
}

const EmpreendimentosCuryRouteWithChildren =
  EmpreendimentosCuryRoute._addFileChildren(EmpreendimentosCuryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CarreirasRoute: CarreirasRoute,
  ContatoRoute: ContatoRoute,
  DesignSystemRoute: DesignSystemRoute,
  ManifestDotjsonRoute: ManifestDotjsonRoute,
  ManifestoRoute: ManifestoRoute,
  MetodoRoute: MetodoRoute,
  OnboardingRoute: OnboardingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SimulacaoRoute: SimulacaoRoute,
  SitemapImagensDotxmlRoute: SitemapImagensDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ConstrutorasCuryRoute: ConstrutorasCuryRoute,
  EmpreendimentosIdRoute: EmpreendimentosIdRoute,
  EmpreendimentosCuryRoute: EmpreendimentosCuryRouteWithChildren,
  EnSplatRoute: EnSplatRoute,
  EsSplatRoute: EsSplatRoute,
  LpSlugRoute: LpSlugRoute,
  EmpreendimentosIndexRoute: EmpreendimentosIndexRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksAdvisorWatchdogRoute: ApiPublicHooksAdvisorWatchdogRoute,
  ApiPublicHooksAutomationRollupRoute: ApiPublicHooksAutomationRollupRoute,
  ApiPublicHooksMarketCollectorRoute: ApiPublicHooksMarketCollectorRoute,
  ApiPublicHooksOutboxWorkerRoute: ApiPublicHooksOutboxWorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
